{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3c4befed",
   "metadata": {},
   "outputs": [],
   "source": [
    "from bs4 import BeautifulSoup\n",
    "import requests"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "3e59f51b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import json"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d5228acd",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "d777a8d4",
   "metadata": {},
   "outputs": [],
   "source": [
    "base_url = 'https://www.amazon.com'\n",
    "product_page_url = f\"{base_url}/s?i=specialty-aps&srs=17296221011&rh=n%3A17296221011&fs=true&qid=1680239013&ref=sr_pg_2&page=\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "19bfe5c1",
   "metadata": {},
   "outputs": [],
   "source": [
    "HEADERS = ({'User-Agent':\n",
    "        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36',\n",
    "        'Accept-Language': 'en-US, en;q=0.5'})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7facd7ff",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "d7b1dee9",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "##image\n",
    "def getImage(div):\n",
    "    try:\n",
    "        return div.find('img', {'class': 's-image'}).attrs['src']\n",
    "    except:\n",
    "        return ''\n",
    "\n",
    "## returns https://m.media-amazon.com/images/I/71ok9jCkgVL._AC_UY218_.jpg"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "8b4bf018",
   "metadata": {},
   "outputs": [],
   "source": [
    "## title\n",
    "def getTitle(div):\n",
    "    try:\n",
    "        return div.find('h2').text.strip()\n",
    "    except:\n",
    "        return ''\n",
    "\n",
    "##returns Lessons in Chemistry: A Novel"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "be2ee1d4",
   "metadata": {},
   "outputs": [],
   "source": [
    "## prod link\n",
    "def getProdLink(div):\n",
    "    return div.find('span', {'data-component-type': 's-product-image'}).find('a').attrs[\"href\"]\n",
    "\n",
    "## returns /Lessons-in-Chemistry-A-Novel/dp/B09BBK79VB/ref=sr_1_1?qid=1680240999&sr=8-1&srs=17296221011"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "b0025c52",
   "metadata": {},
   "outputs": [],
   "source": [
    "## author\n",
    "def getAuthor(div):\n",
    "    try:\n",
    "        return div.find('h2').next_sibling()[0].text.replace('by', '').strip()\n",
    "    except:\n",
    "        return ''\n",
    "\n",
    "## returns Bonnie Garmus, Miranda Raison, et al."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "53e5282b",
   "metadata": {},
   "outputs": [],
   "source": [
    "## rating\n",
    "def getRating(div):\n",
    "    try:\n",
    "        return div.find('div', {'class': 'a-row a-size-small'}).find('span', {'class': 'a-size-base'}).text\n",
    "    except:\n",
    "        return '0'\n",
    "\n",
    "## returns 4.6"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "8bbbc2d7",
   "metadata": {},
   "outputs": [],
   "source": [
    "## total reviews\n",
    "def getReviewCount(div):\n",
    "    try:\n",
    "        return div.find('div', {'class': 'a-row a-size-small'}).find('span').next_sibling.attrs[\"aria-label\"]\n",
    "    except:\n",
    "        return '0'\n",
    "\n",
    "## returns 126,027"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "05feea79",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "e5c77601",
   "metadata": {},
   "outputs": [],
   "source": [
    "## publisher\n",
    "def getPublisher(product_soup):\n",
    "    try:\n",
    "        return product_soup.find('div', {'id': 'rpi-attribute-audiobook_details-publisher'}).find(\n",
    "            'div', {'class': 'rpi-attribute-value'}).text.strip()\n",
    "    except:\n",
    "        try:\n",
    "            return product_soup.find('div', {'id': 'rpi-attribute-book_details-publisher'}).find(\n",
    "                'div', {'class': 'rpi-attribute-value'}).text.strip()\n",
    "        except:\n",
    "            pass\n",
    "    return ''\n",
    "\n",
    "## returns Random House Audio"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "fc618490",
   "metadata": {},
   "outputs": [],
   "source": [
    "## publish date\n",
    "def getPublishDate(product_soup):\n",
    "    try:\n",
    "        return product_soup.find('div', {'id': 'rpi-attribute-audiobook_details-release-date'}).find(\n",
    "            'div', {'class': 'rpi-attribute-value'}).text.strip()\n",
    "    except:\n",
    "        try:\n",
    "            return product_soup.find('div', {'id': 'rpi-attribute-book_details-release-date'}).find(\n",
    "                'div', {'class': 'rpi-attribute-value'}).text.strip()\n",
    "        except:\n",
    "            pass\n",
    "        return 'Jan 1, 1970'\n",
    "\n",
    "##returns April 5, 2022"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "12287b62",
   "metadata": {},
   "outputs": [],
   "source": [
    "##prices\n",
    "def getPrices(product_soup):\n",
    "    try:\n",
    "        prices_list = product_soup.find_all('li', { 'class': 'swatchElement' })\n",
    "        prices = {}\n",
    "        for p in prices_list:\n",
    "            tokens = p.find('a').text.split()\n",
    "            type, cost = tokens[0], tokens[-1]\n",
    "            prices[type] = cost\n",
    "        return prices\n",
    "    except:\n",
    "        return {}\n",
    "\n",
    "\n",
    "##returns {'Kindle': '$14.99',\n",
    "##         'Audiobook': '$0.00',\n",
    "##         'Hardcover': '$17.99',\n",
    "##         'Paperback': '$27.90',\n",
    "##        'Spiral-bound': '$37.81'}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "21df3298",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "d6bc2ba8",
   "metadata": {},
   "outputs": [],
   "source": [
    "# breakdown for ratings\n",
    "# 1, 2, 3, 4, 5"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "id": "3e2d5944",
   "metadata": {},
   "outputs": [],
   "source": [
    "def getRatingBreakdown(product_soup):\n",
    "    try:\n",
    "        return [p.text.strip()[:-1] for p in product_soup.find(\n",
    "            'table', {'id': 'histogramTable'}\n",
    "        ).find_all('span', { 'class': 'a-size-base' })[1::2][::-1]]\n",
    "    except:\n",
    "        return [0,0,0,0,0]\n",
    "\n",
    "## return ['1', '1', '6', '20', '72']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "1175ea1c",
   "metadata": {},
   "outputs": [],
   "source": [
    "## ranking\n",
    "def getRanking(product_soup):\n",
    "    ranking_tr = []\n",
    "    try:\n",
    "        ranking_tr = product_soup.find(\n",
    "            'span', {'id': 'audibleProductDetailsSalesRank'}\n",
    "        ).find('td').find('span').find_all('span')\n",
    "    except:\n",
    "        try:\n",
    "            ranking_tr = product_soup.find(\n",
    "                'ul', {'class': 'a-unordered-list a-nostyle a-vertical a-spacing-none detail-bullet-list'}\n",
    "            ).find('ul').find_all('li')\n",
    "        except:\n",
    "            pass\n",
    "    return [t.text for t in ranking_tr]\n",
    "\n",
    "##returns ['#5 in Audible Books & Originals (See Top 100 in Audible Books & Originals)',\n",
    "##         '#1 in Historical Fiction (Books)',\n",
    "##         '#1 in Historical Fiction (Audible Books & Originals)',\n",
    "##         '#1 in Humorous Fiction & Satire']\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "356ea0a7",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "70bb4162",
   "metadata": {},
   "outputs": [],
   "source": [
    "pages = 7"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "d355ab2c",
   "metadata": {},
   "outputs": [],
   "source": [
    "result = []"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "d0f67520",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Lessons in Chemistry: A Novel\n",
      "Tomorrow, and Tomorrow, and Tomorrow: A novel\n",
      "Demon Copperhead: A Novel\n",
      "Remarkably Bright Creatures: A Novel\n",
      "Reminders of Him: A Novel\n",
      "Mad Honey: A Novel\n",
      "Horse: A Novel\n",
      "I'm Glad My Mom Died\n",
      "Fairy Tale\n",
      "Lighter: Let Go of the Past, Connect with the Present, and Expand the Future\n",
      "Finding Me: A Memoir\n",
      "Our Missing Hearts: A Novel\n",
      "An Immense World: How Animal Senses Reveal the Hidden Realms Around Us\n",
      "Surrender: 40 Songs, One Story\n",
      "Carrie Soto Is Back: A Novel\n",
      "Friends, Lovers, and the Big Terrible Thing: A Memoir\n",
      "The Marriage Portrait: A novel\n",
      "Bittersweet (Oprah's Book Club): How Sorrow and Longing Make Us Whole\n",
      "And There Was Light: Abraham Lincoln and the American Struggle\n",
      "The Song of the Cell: An Exploration of Medicine and the New Human\n",
      "Starry Messenger: Cosmic Perspectives on Civilization\n",
      "Solito: A Memoir\n",
      "Sea of Tranquility: A novel\n",
      "Cinema Speculation\n",
      "What If? 2: Additional Serious Scientific Answers to Absurd Hypothetical Questions\n",
      "The Winners: A Novel\n",
      "Take My Hand\n",
      "All the Broken Places: A Novel\n",
      "The Escape Artist: The Man Who Broke Out of Auschwitz to Warn the World\n",
      "The Maid: A Novel\n",
      "Killers of a Certain Age\n",
      "Visual Thinking: The Hidden Gifts of People Who Think in Pictures, Patterns, and Abstractions\n",
      "Part of Your World\n",
      "The Paris Apartment: A Novel\n",
      "The Overnight Guest: A Novel\n",
      "Signal Fires: A novel\n",
      "All My Rage: A Novel\n",
      "Stolen Focus: Why You Can't Pay Attention--and How to Think Deeply Again\n",
      "Young Mungo\n",
      "The Bodyguard: A Novel\n",
      "I'll Show Myself Out: Essays on Midlife and Motherhood\n",
      "River of the Gods: Genius, Courage, and Betrayal in the Search for the Source of the Nile\n",
      "What My Bones Know: A Memoir of Healing from Complex Trauma\n",
      "The Christie Affair: A Novel\n",
      "The German Wife: A Novel\n",
      "By Hands Now Known: Jim Crow's Legal Executioners\n",
      "The Door of No Return\n",
      "City on Fire: A Novel\n",
      "The Whalebone Theatre: A novel\n",
      "Nightcrawling: A Novel\n",
      "City on Fire: A Novel\n",
      "Black Cake: A Novel\n",
      "Memphis: A Novel\n",
      "When in Rome: A Novel\n",
      "Like a Rolling Stone: A Memoir\n",
      "Emotional Inheritance: A Therapist, Her Patients, and the Legacy of Trauma\n",
      "Now Is Not the Time to Panic: A Novel\n",
      "Unmasked: My Life Solving America's Cold Cases\n",
      "Prisoners of the Castle: An Epic Story of Survival and Escape from Colditz, the Nazis' Fortress Prison\n",
      "Hello, Molly!: A Memoir\n",
      "Things We Do in the Dark: A Novel\n",
      "How Not to Drown in a Glass of Water: A Novel\n",
      "How to Raise an Antiracist\n",
      "A Lady's Guide to Fortune-Hunting: A Novel\n",
      "Shutter\n",
      "Book Lovers\n",
      "Bad City: Peril and Power in the City of Angels\n",
      "Butts: A Backstory\n",
      "Raising Lazarus: Hope, Justice, and the Future of America's Overdose Crisis\n",
      "The Last Slave Ship: The True Story of How Clotilda Was Found, Her Descendants, and an Extraordinary Reckoning\n",
      "Gilded Mountain: A Novel\n",
      "The Man Who Could Move Clouds: A Memoir\n",
      "In Love: A Memoir of Love and Loss\n",
      "The Come Up: An Oral History of the Rise of Hip-Hop\n",
      "The Kaiju Preservation Society\n",
      "Our Crooked Hearts: A Novel\n",
      "How to Speak Whale: A Voyage into the Future of Animal Communication\n",
      "Corrections in Ink: A Memoir\n",
      "Acceptance: A Memoir\n",
      "Tanqueray\n",
      "Like, Comment, Subscribe: Inside YouTube's Chaotic Rise to World Domination\n",
      "The Hookup Plan\n",
      "Lavender House: A Novel\n",
      "His Name Is George Floyd: One Man's Life and the Struggle for Racial Justice\n",
      "The Unsinkable Greta James: A Novel\n",
      "The First Kennedys: The Humble Roots of an American Dynasty\n",
      "The Two Lives of Sara: A Novel\n",
      "Token Black Girl: A Memoir\n",
      "Cabin Fever: The Harrowing Journey of a Cruise Ship at the Dawn of a Pandemic\n",
      "The Final Strife: Book One of The Ending Fire Trilogy\n",
      "Paris Daillencourt Is About to Crumble (Winner Bakes All Book 2)\n",
      "NSFW: A Novel\n",
      "Sleepwalk: A Novel\n",
      "The Year of the Horses: A Memoir\n",
      "The Other Mother: A Novel\n",
      "How to Kill Your Family: A Novel\n",
      "Thank You for Listening: A Novel\n",
      "Such Big Dreams: A Novel\n",
      "The Community: A Memoir\n",
      "By the Book-A Meant To Be Novel\n"
     ]
    }
   ],
   "source": [
    "for p in range(1, pages+1):\n",
    "    page_url = f\"{product_page_url}{p}\"\n",
    "    \n",
    "    resp = requests.get(page_url, headers=HEADERS)\n",
    "    soup = BeautifulSoup(resp.content, \"html\")\n",
    "    book_items = soup.find_all(\"div\", attrs={\"data-component-type\":'s-search-result'})\n",
    "    \n",
    "    for book in book_items:\n",
    "        book_details  = {}\n",
    "        book_details[\"image\"] = getImage(book)\n",
    "        book_details[\"title\"] = getTitle(book)\n",
    "        book_details[\"author\"] = getAuthor(book)\n",
    "        book_details[\"rating\"] = getRating(book)\n",
    "        book_details[\"review_count\"] = getReviewCount(book)\n",
    "        try:\n",
    "            link = getProdLink(book)\n",
    "            book_details[\"product_link\"] = link\n",
    "            product_url = f\"{base_url}{link}\"\n",
    "\n",
    "\n",
    "            prod_resp = requests.get(product_url, headers=HEADERS)\n",
    "            product_soup = BeautifulSoup(prod_resp.content, 'html')\n",
    "\n",
    "            book_details[\"publisher\"] = getPublisher(product_soup)\n",
    "            book_details[\"publish_date\"] = getPublishDate(product_soup)\n",
    "            book_details[\"prices\"] = getPrices(product_soup)\n",
    "            book_details[\"rating_breakdown\"] = getRatingBreakdown(product_soup)\n",
    "            book_details[\"ranking\"] = getRanking(product_soup)\n",
    "        except:\n",
    "            print(\"couldnt load product page\")\n",
    "            pass\n",
    "        result.append(book_details)\n",
    "        print(book_details[\"title\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "29fd40f9",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "id": "52d67c89",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[{'image': 'https://m.media-amazon.com/images/I/91HwoNG6iqL._AC_UY218_.jpg',\n",
       "  'title': 'Tomorrow, and Tomorrow, and Tomorrow: A novel',\n",
       "  'author': 'Gabrielle Zevin  | Jul 5, 2022',\n",
       "  'rating': '4.4',\n",
       "  'review_count': '38,021',\n",
       "  'product_link': '/Tomorrow-novel-Gabrielle-Zevin-ebook/dp/B09JBCGQB8/ref=sr_1_2?qid=1680261196&sr=8-2&srs=17296221011',\n",
       "  'publisher': 'Knopf',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$13.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$15.49',\n",
       "   'Paperback': '$25.49'},\n",
       "  'rating_breakdown': ['1', '2', '10', '28', '59'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/617uZq23IPL._AC_UY218_.jpg',\n",
       "  'title': 'Reminders of Him: A Novel',\n",
       "  'author': 'Colleen Hoover  | Jan 18, 2022',\n",
       "  'rating': '4.7',\n",
       "  'review_count': '207,191',\n",
       "  'product_link': '/Reminders-Him-Novel-Colleen-Hoover/dp/1542025605/ref=sr_1_5?qid=1680261196&sr=8-5&srs=17296221011',\n",
       "  'publisher': '',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$0.00',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Library': '$37.78',\n",
       "   'Paperback': '$9.57',\n",
       "   'Audio': '$14.99'},\n",
       "  'rating_breakdown': ['1', '1', '4', '16', '78'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81P0W3YcvXL._AC_UY218_.jpg',\n",
       "  'title': 'Horse: A Novel',\n",
       "  'author': 'Geraldine Brooks  | Jun 14, 2022',\n",
       "  'rating': '4.6',\n",
       "  'review_count': '21,133',\n",
       "  'product_link': '/Horse-Novel-Geraldine-Brooks-ebook/dp/B09G9D94VW/ref=sr_1_7?qid=1680261196&sr=8-7&srs=17296221011',\n",
       "  'publisher': 'Viking',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$13.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$22.99',\n",
       "   'Paperback': '$26.99'},\n",
       "  'rating_breakdown': ['2', '2', '5', '20', '71'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/91lgm-V5fqL._AC_UY218_.jpg',\n",
       "  'title': 'Lighter: Let Go of the Past, Connect with the Present, and Expand the Future',\n",
       "  'author': 'Yung Pueblo  | Oct 4, 2022',\n",
       "  'rating': '4.7',\n",
       "  'review_count': '1,330',\n",
       "  'product_link': '/Lighter-Connect-Present-Expand-Future/dp/0593233174/ref=sr_1_10?qid=1680261196&sr=8-10&srs=17296221011',\n",
       "  'publisher': 'Harmony',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$13.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$15.88',\n",
       "   'Paperback': '$35.30',\n",
       "   'Spiral-bound': '$31.96'},\n",
       "  'rating_breakdown': ['2', '2', '4', '10', '82'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81xQjuzayAL._AC_UY218_.jpg',\n",
       "  'title': 'Our Missing Hearts: A Novel',\n",
       "  'author': 'Celeste Ng  | Oct 4, 2022',\n",
       "  'rating': '4.3',\n",
       "  'review_count': '12,135',\n",
       "  'product_link': '/Our-Missing-Hearts-Celeste-Ng-ebook/dp/B09QBYCC3J/ref=sr_1_12?qid=1680261196&sr=8-12&srs=17296221011',\n",
       "  'publisher': 'Penguin Press',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$15.19',\n",
       "   'Paperback': '$21.49',\n",
       "   'Audio': '$30.06'},\n",
       "  'rating_breakdown': ['2', '4', '13', '28', '53'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/A1qnlFuEGtL._AC_UY218_.jpg',\n",
       "  'title': 'Carrie Soto Is Back: A Novel',\n",
       "  'author': 'Taylor Jenkins Reid  | Aug 30, 2022',\n",
       "  'rating': '4.4',\n",
       "  'review_count': '20,688',\n",
       "  'product_link': '/Carrie-Soto-Back-Taylor-Jenkins-ebook/dp/B09SNYDGR9/ref=sr_1_15?qid=1680261196&sr=8-15&srs=17296221011',\n",
       "  'publisher': 'Ballantine Books',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$13.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$17.98',\n",
       "   'Paperback': '$18.00',\n",
       "   'Audio': '$32.04'},\n",
       "  'rating_breakdown': ['1', '2', '9', '31', '57'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T2/images/I/91fTEzD2QOL._AC_UY218_.jpg',\n",
       "  'title': 'The Marriage Portrait: A novel',\n",
       "  'author': \"Maggie O'Farrell  | Sep 6, 2022\",\n",
       "  'rating': '4.3',\n",
       "  'review_count': '14,119',\n",
       "  'product_link': '/Marriage-Portrait-novel-Maggie-OFarrell-ebook/dp/B09RTYQW2S/ref=sr_1_17?qid=1680261260&sr=8-17&srs=17296221011',\n",
       "  'publisher': 'Knopf',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$18.78',\n",
       "   'Paperback': '$15.30'},\n",
       "  'rating_breakdown': ['2', '3', '13', '31', '51'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T2/images/I/81d3qLZSKlL._AC_UY218_.jpg',\n",
       "  'title': \"Bittersweet (Oprah's Book Club): How Sorrow and Longing Make Us Whole\",\n",
       "  'author': 'Susan Cain  | Apr 5, 2022',\n",
       "  'rating': '4.5',\n",
       "  'review_count': '1,360',\n",
       "  'product_link': '/Bittersweet-Sorrow-Longing-Make-Whole/dp/0451499786/ref=sr_1_18?qid=1680261260&sr=8-18&srs=17296221011',\n",
       "  'publisher': 'Crown',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$15.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$14.63',\n",
       "   'Paperback': '$18.00',\n",
       "   'Audio': '$24.98'},\n",
       "  'rating_breakdown': ['2', '2', '8', '17', '71'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T2/images/I/81pZkGGlbjL._AC_UY218_.jpg',\n",
       "  'title': 'The Song of the Cell: An Exploration of Medicine and the New Human',\n",
       "  'author': 'Siddhartha Mukherjee  | Oct 25, 2022',\n",
       "  'rating': '4.7',\n",
       "  'review_count': '1,282',\n",
       "  'product_link': '/Song-Cell-Exploration-Medicine-Human/dp/1982117354/ref=sr_1_20?qid=1680261260&sr=8-20&srs=17296221011',\n",
       "  'publisher': 'Scribner',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$16.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$17.89',\n",
       "   'Paperback': '$21.00',\n",
       "   'Audio': '$37.66'},\n",
       "  'rating_breakdown': ['1', '1', '5', '16', '77'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T2/images/I/81Xs3j5UqAL._AC_UY218_.jpg',\n",
       "  'title': 'Sea of Tranquility: A novel',\n",
       "  'author': 'Emily St. John Mandel  | Apr 5, 2022',\n",
       "  'rating': '4.3',\n",
       "  'review_count': '19,443',\n",
       "  'product_link': '/Sea-Tranquility-Emily-John-Mandel-ebook/dp/B099DRHTLX/ref=sr_1_23?qid=1680261260&sr=8-23&srs=17296221011',\n",
       "  'publisher': 'Vintage',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$11.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$17.00',\n",
       "   'Paperback': '$15.30',\n",
       "   'Audio': '$32.95'},\n",
       "  'rating_breakdown': ['1', '3', '12', '32', '52'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T2/images/I/81TrZAPVcCL._AC_UY218_.jpg',\n",
       "  'title': 'Cinema Speculation',\n",
       "  'author': 'Quentin Tarantino  | Nov 1, 2022',\n",
       "  'rating': '4.5',\n",
       "  'review_count': '1,250',\n",
       "  'product_link': '/Cinema-Speculation-Quentin-Tarantino/dp/0063112582/ref=sr_1_24?qid=1680261260&sr=8-24&srs=17296221011',\n",
       "  'publisher': 'Harper',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$15.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$21.86',\n",
       "   'Paperback': '$21.99',\n",
       "   'Audio': '$33.27'},\n",
       "  'rating_breakdown': ['1', '2', '6', '20', '70'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T2/images/I/71xD1Mog4AL._AC_UY218_.jpg',\n",
       "  'title': 'What If? 2: Additional Serious Scientific Answers to Absurd Hypothetical Questions',\n",
       "  'author': 'Part of: What If? (2 books)   |  Randall Munroe  | Sep 13, 2022',\n",
       "  'rating': '4.8',\n",
       "  'review_count': '2,276',\n",
       "  'product_link': '/What-Additional-Scientific-Hypothetical-Questions/dp/0525537112/ref=sr_1_25?qid=1680261260&sr=8-25&srs=17296221011',\n",
       "  'publisher': 'Riverhead Books',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$15.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$18.57',\n",
       "   'Paperback': '$19.00'},\n",
       "  'rating_breakdown': ['1', '1', '3', '13', '83'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T2/images/I/91ufGHoA9kL._AC_UY218_.jpg',\n",
       "  'title': 'All the Broken Places: A Novel',\n",
       "  'author': 'John Boyne  | Nov 29, 2022',\n",
       "  'rating': '4.6',\n",
       "  'review_count': '6,196',\n",
       "  'product_link': '/All-Broken-Places-John-Boyne-ebook/dp/B0B14GBSYH/ref=sr_1_28?qid=1680261260&sr=8-28&srs=17296221011',\n",
       "  'publisher': 'Pamela Dorman Books',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$24.33',\n",
       "   'Paperback': '$34.58'},\n",
       "  'rating_breakdown': ['1', '1', '4', '21', '73'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T2/images/I/814h-ay5h4L._AC_UY218_.jpg',\n",
       "  'title': 'The Escape Artist: The Man Who Broke Out of Auschwitz to Warn the World',\n",
       "  'author': 'Jonathan Freedland  | Oct 18, 2022',\n",
       "  'rating': '4.6',\n",
       "  'review_count': '3,360',\n",
       "  'product_link': '/Escape-Artist-Broke-Auschwitz-World-ebook/dp/B09QGSNB53/ref=sr_1_29?qid=1680261260&sr=8-29&srs=17296221011',\n",
       "  'publisher': 'Harper',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$26.09',\n",
       "   'Paperback': '$17.99',\n",
       "   'Audio': '$31.61'},\n",
       "  'rating_breakdown': ['1', '1', '5', '25', '69'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T2/images/I/71FyoSti2xL._AC_UY218_.jpg',\n",
       "  'title': 'Killers of a Certain Age',\n",
       "  'author': 'Deanna Raybourn  | Sep 6, 2022',\n",
       "  'rating': '4.4',\n",
       "  'review_count': '4,470',\n",
       "  'product_link': '/Killers-Certain-Age-Deanna-Raybourn-ebook/dp/B09N6VX4K7/ref=sr_1_31?qid=1680261260&sr=8-31&srs=17296221011',\n",
       "  'publisher': 'Berkley',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$20.49',\n",
       "   'Paperback': '$11.63'},\n",
       "  'rating_breakdown': ['1', '2', '11', '32', '54'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T2/images/I/61J+ySs3bXL._AC_UY218_.jpg',\n",
       "  'title': 'Visual Thinking: The Hidden Gifts of People Who Think in Pictures, Patterns, and Abstractions',\n",
       "  'author': 'Temple Grandin PhD | Oct 11, 2022',\n",
       "  'rating': '4.6',\n",
       "  'review_count': '243',\n",
       "  'product_link': '/Visual-Thinking-Pictures-Patterns-Abstractions/dp/0593418360/ref=sr_1_32?qid=1680261260&sr=8-32&srs=17296221011',\n",
       "  'publisher': 'Riverhead Books',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$15.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$20.42',\n",
       "   'Paperback': '$16.24'},\n",
       "  'rating_breakdown': ['1', '4', '7', '13', '74'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/71RBQViFfPL._AC_UY218_.jpg',\n",
       "  'title': 'Part of Your World',\n",
       "  'author': 'Ab Jimenez  | Apr 19, 2022',\n",
       "  'rating': '4.6',\n",
       "  'review_count': '8,308',\n",
       "  'product_link': '/Part-Your-World-Abby-Jimenez/dp/1538704374/ref=sr_1_33?qid=1680261323&sr=8-33&srs=17296221011',\n",
       "  'publisher': 'Forever',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$10.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Library': '$16.89',\n",
       "   'Paperback': '$9.99',\n",
       "   'Audio': '$31.70'},\n",
       "  'rating_breakdown': ['0', '1', '7', '26', '66'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81U4zD8QMsL._AC_UY218_.jpg',\n",
       "  'title': 'The Overnight Guest: A Novel',\n",
       "  'author': 'Heather Gudenkauf  | Jan 25, 2022',\n",
       "  'rating': '4.3',\n",
       "  'review_count': '7,245',\n",
       "  'product_link': '/Overnight-Guest-Novel-Heather-Gudenkauf-ebook/dp/B08ZSQLZBS/ref=sr_1_35?qid=1680261323&sr=8-35&srs=17296221011',\n",
       "  'publisher': 'Park Row',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$12.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$17.99',\n",
       "   'Paperback': '$12.49',\n",
       "   'Audio': '$31.44'},\n",
       "  'rating_breakdown': ['1', '2', '11', '33', '53'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/71YtiahbLyL._AC_UY218_.jpg',\n",
       "  'title': 'Signal Fires: A novel',\n",
       "  'author': 'Dani Shapiro  | Oct 18, 2022',\n",
       "  'rating': '4.3',\n",
       "  'review_count': '2,725',\n",
       "  'product_link': '/Signal-Fires-novel-Dani-Shapiro-ebook/dp/B09Q8FNM11/ref=sr_1_36?qid=1680261323&sr=8-36&srs=17296221011',\n",
       "  'publisher': 'Knopf',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$18.99',\n",
       "   'Paperback': '$27.44'},\n",
       "  'rating_breakdown': ['2', '3', '12', '30', '52'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/913SV5CtsVL._AC_UY218_.jpg',\n",
       "  'title': 'All My Rage: A Novel',\n",
       "  'author': 'Sabaa Tahir  | Mar 7, 2023',\n",
       "  'rating': '4.7',\n",
       "  'review_count': '1,609',\n",
       "  'product_link': '/All-My-Rage-Sabaa-Tahir/dp/0593202368/ref=sr_1_37?qid=1680261323&sr=8-37&srs=17296221011',\n",
       "  'publisher': 'Razorbill',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$8.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$10.49',\n",
       "   'Paperback': '$11.69'},\n",
       "  'rating_breakdown': ['1', '1', '4', '18', '76'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/71Y85lJdsHL._AC_UY218_.jpg',\n",
       "  'title': \"Stolen Focus: Why You Can't Pay Attention--and How to Think Deeply Again\",\n",
       "  'author': 'Johann Hari  | Jan 24, 2023',\n",
       "  'rating': '4.4',\n",
       "  'review_count': '4,443',\n",
       "  'product_link': '/Stolen-Focus-Attention-Think-Deeply/dp/0593138538/ref=sr_1_38?qid=1680261323&sr=8-38&srs=17296221011',\n",
       "  'publisher': 'Crown',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$20.99',\n",
       "   'Paperback': '$16.20'},\n",
       "  'rating_breakdown': ['2', '3', '9', '23', '64'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/71zJL1N2sgL._AC_UY218_.jpg',\n",
       "  'title': 'Young Mungo',\n",
       "  'author': 'Douglas Stuart  | Mar 21, 2023',\n",
       "  'rating': '4.5',\n",
       "  'review_count': '1,739',\n",
       "  'product_link': '/Young-Mungo-Douglas-Stuart/dp/0802162126/ref=sr_1_39?qid=1680261323&sr=8-39&srs=17296221011',\n",
       "  'publisher': 'Grove Press',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$9.45', 'Hardcover': '$14.89', 'Paperback': '$16.20'},\n",
       "  'rating_breakdown': ['2', '2', '7', '21', '69'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/714vv1T7weL._AC_UY218_.jpg',\n",
       "  'title': \"I'll Show Myself Out: Essays on Midlife and Motherhood\",\n",
       "  'author': 'Jessi Klein  | Apr 26, 2022',\n",
       "  'rating': '4.2',\n",
       "  'review_count': '732',\n",
       "  'product_link': '/Ill-Show-Myself-Out-Motherhood-ebook/dp/B0995Y2YGR/ref=sr_1_41?qid=1680261323&sr=8-41&srs=17296221011',\n",
       "  'publisher': 'Harper',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$11.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$17.65',\n",
       "   'Paperback': '$18.99',\n",
       "   'Audio': '$23.45'},\n",
       "  'rating_breakdown': ['3', '5', '14', '26', '52'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/71PSosAox1L._AC_UY218_.jpg',\n",
       "  'title': 'The Christie Affair: A Novel',\n",
       "  'author': 'Nina de Gramont  | Feb 1, 2022',\n",
       "  'rating': '4.3',\n",
       "  'review_count': '9,364',\n",
       "  'product_link': '/Christie-Affair-Novel-Nina-Gramont-ebook/dp/B092T9DMJ5/ref=sr_1_44?qid=1680261323&sr=8-44&srs=17296221011',\n",
       "  'publisher': \"St. Martin's Press\",\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$11.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$14.69',\n",
       "   'Paperback': '$17.99',\n",
       "   'Audio': '$39.99'},\n",
       "  'rating_breakdown': ['1', '3', '14', '32', '50'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81XWMjUuzML._AC_UY218_.jpg',\n",
       "  'title': 'The German Wife: A Novel',\n",
       "  'author': 'Kelly Rimmer  | Jun 28, 2022',\n",
       "  'rating': '4.5',\n",
       "  'review_count': '3,260',\n",
       "  'product_link': '/German-Wife-Novel-Kelly-Rimmer-ebook/dp/B09FGT2V4F/ref=sr_1_45?qid=1680261323&sr=8-45&srs=17296221011',\n",
       "  'publisher': 'Graydon House',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$23.49',\n",
       "   'Paperback': '$13.84',\n",
       "   'Spiral-bound': '$31.14',\n",
       "   'Audio': '$33.27'},\n",
       "  'rating_breakdown': ['1', '1', '6', '26', '66'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/71Eat8UjvHL._AC_UY218_.jpg',\n",
       "  'title': \"By Hands Now Known: Jim Crow's Legal Executioners\",\n",
       "  'author': 'Margaret A. Burnham  | Sep 27, 2022',\n",
       "  'rating': '4.7',\n",
       "  'review_count': '85',\n",
       "  'product_link': '/Hands-Now-Known-Crows-Executioners/dp/0393867854/ref=sr_1_46?qid=1680261323&sr=8-46&srs=17296221011',\n",
       "  'publisher': 'W. W. Norton & Company',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$9.66',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$15.27',\n",
       "   'Paperback': '$19.95'},\n",
       "  'rating_breakdown': ['0', '2', '4', '20', '74'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81peOOwSM6L._AC_UY218_.jpg',\n",
       "  'title': 'The Door of No Return',\n",
       "  'author': 'Kwame Alexander  | Sep 27, 2022',\n",
       "  'rating': '4.6',\n",
       "  'review_count': '137',\n",
       "  'product_link': '/Door-No-Return-Kwame-Alexander/dp/0316441864/ref=sr_1_47?qid=1680261323&sr=8-47&srs=17296221011',\n",
       "  'publisher': 'Little, Brown Books for Young Readers',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$9.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$10.47',\n",
       "   'Audio': '$32.55'},\n",
       "  'rating_breakdown': ['1', '1', '8', '14', '76'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/71kmzOiW16L._AC_UY218_.jpg',\n",
       "  'title': 'City on Fire: A Novel',\n",
       "  'author': 'Book 1 of 2: The City   |  Don Winslow  | Apr 26, 2022',\n",
       "  'rating': '4.3',\n",
       "  'review_count': '7,650',\n",
       "  'product_link': '/City-Fire-Novel-Don-Winslow-ebook/dp/B09131XKCQ/ref=sr_1_48?qid=1680261323&sr=8-48&srs=17296221011',\n",
       "  'publisher': 'William Morrow',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$14.99',\n",
       "   'Paperback': '$16.33',\n",
       "   'Audio': '$34.86'},\n",
       "  'rating_breakdown': ['2', '3', '11', '30', '54'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81DE33NaPNL._AC_UY218_.jpg',\n",
       "  'title': 'The Whalebone Theatre: A novel',\n",
       "  'author': 'Joanna Quinn  | Oct 4, 2022',\n",
       "  'rating': '4.4',\n",
       "  'review_count': '1,249',\n",
       "  'product_link': '/Whalebone-Theatre-novel-Joanna-Quinn-ebook/dp/B09LHBD39F/ref=sr_1_49?qid=1680261389&sr=8-49&srs=17296221011',\n",
       "  'publisher': 'Knopf',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$15.22',\n",
       "   'Paperback': '$24.65'},\n",
       "  'rating_breakdown': ['2', '3', '9', '27', '59'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/71kmzOiW16L._AC_UY218_.jpg',\n",
       "  'title': 'City on Fire: A Novel',\n",
       "  'author': 'Book 1 of 2: The City   |  Don Winslow  | Apr 26, 2022',\n",
       "  'rating': '4.3',\n",
       "  'review_count': '7,650',\n",
       "  'product_link': '/City-Fire-Novel-Don-Winslow-ebook/dp/B09131XKCQ/ref=sr_1_51?qid=1680261389&sr=8-51&srs=17296221011',\n",
       "  'publisher': 'William Morrow',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$14.99',\n",
       "   'Paperback': '$16.33',\n",
       "   'Audio': '$34.86'},\n",
       "  'rating_breakdown': ['2', '3', '11', '30', '54'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81jEc6olAeL._AC_UY218_.jpg',\n",
       "  'title': 'Memphis: A Novel',\n",
       "  'author': 'Tara M. Stringfellow  | Apr 5, 2022',\n",
       "  'rating': '4.5',\n",
       "  'review_count': '3,551',\n",
       "  'product_link': '/Memphis-Novel-Tara-M-Stringfellow-ebook/dp/B093YSLSJD/ref=sr_1_53?qid=1680261389&sr=8-53&srs=17296221011',\n",
       "  'publisher': 'The Dial Press',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$13.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$14.11',\n",
       "   'Paperback': '$11.69'},\n",
       "  'rating_breakdown': ['1', '2', '8', '26', '63'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/71877Z+S0nL._AC_UY218_.jpg',\n",
       "  'title': 'When in Rome: A Novel',\n",
       "  'author': 'Sarah Adams  | Sep 20, 2022',\n",
       "  'rating': '4.3',\n",
       "  'review_count': '2,446',\n",
       "  'product_link': '/When-Rome-Novel-Sarah-Adams-ebook/dp/B09QJM783S/ref=sr_1_54?qid=1680261389&sr=8-54&srs=17296221011',\n",
       "  'publisher': 'Dell',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$7.99', 'Audiobook': '$0.00', 'Paperback': '$12.91'},\n",
       "  'rating_breakdown': ['1', '3', '14', '32', '50'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/814YCGJPGgL._AC_UY218_.jpg',\n",
       "  'title': 'Like a Rolling Stone: A Memoir',\n",
       "  'author': 'Jann  Wenner  | Sep 13, 2022',\n",
       "  'rating': '4.3',\n",
       "  'review_count': '1,178',\n",
       "  'product_link': '/Like-Rolling-Stone-Jann-Wenner-ebook/dp/B09PL5JG93/ref=sr_1_55?qid=1680261389&sr=8-55&srs=17296221011',\n",
       "  'publisher': 'Little, Brown and Company',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$16.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$18.29',\n",
       "   'Paperback': '$16.99',\n",
       "   'Audio': '$55.00'},\n",
       "  'rating_breakdown': ['4', '4', '9', '22', '62'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81wxhBTc+dL._AC_UY218_.jpg',\n",
       "  'title': 'Emotional Inheritance: A Therapist, Her Patients, and the Legacy of Trauma',\n",
       "  'author': 'Galit Atlas  | Jan 25, 2022',\n",
       "  'rating': '4.5',\n",
       "  'review_count': '658',\n",
       "  'product_link': '/Emotional-Inheritance-Therapist-Patients-Legacy-ebook/dp/B093ZPV3RG/ref=sr_1_56?qid=1680261389&sr=8-56&srs=17296221011',\n",
       "  'publisher': 'Little, Brown Spark',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$13.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$22.99',\n",
       "   'Paperback': '$18.99',\n",
       "   'Audio': '$31.70'},\n",
       "  'rating_breakdown': ['2', '2', '5', '19', '71'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/91KuSJemvGL._AC_UY218_.jpg',\n",
       "  'title': \"Prisoners of the Castle: An Epic Story of Survival and Escape from Colditz, the Nazis' Fortress Prison\",\n",
       "  'author': 'Ben Macintyre  | Sep 13, 2022',\n",
       "  'rating': '4.6',\n",
       "  'review_count': '1,695',\n",
       "  'product_link': '/Prisoners-Castle-Survival-Colditz-Fortress-ebook/dp/B09NLPP1CP/ref=sr_1_59?qid=1680261389&sr=8-59&srs=17296221011',\n",
       "  'publisher': 'Crown',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$13.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$17.26',\n",
       "   'Paperback': '$26.91',\n",
       "   'Audio': '$33.53'},\n",
       "  'rating_breakdown': ['1', '1', '6', '24', '68'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/71T4RReoaML._AC_UY218_.jpg',\n",
       "  'title': 'Things We Do in the Dark: A Novel',\n",
       "  'author': 'Jennifer Hillier  | Jul 19, 2022',\n",
       "  'rating': '4.2',\n",
       "  'review_count': '5,309',\n",
       "  'product_link': '/Things-We-Do-Dark-Novel-ebook/dp/B09CNF5JK3/ref=sr_1_61?qid=1680261389&sr=8-61&srs=17296221011',\n",
       "  'publisher': 'Minotaur Books',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$17.29',\n",
       "   'Paperback': '$18.00'},\n",
       "  'rating_breakdown': ['1', '2', '14', '39', '43'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/91VddZyY4YL._AC_UY218_.jpg',\n",
       "  'title': 'How to Raise an Antiracist',\n",
       "  'author': 'Ibram X. Kendi  | Jun 14, 2022',\n",
       "  'rating': '4.7',\n",
       "  'review_count': '173',\n",
       "  'product_link': '/How-Raise-Antiracist-Ibram-Kendi/dp/059324253X/ref=sr_1_63?qid=1680261389&sr=8-63&srs=17296221011',\n",
       "  'publisher': 'One World',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$17.22',\n",
       "   'Paperback': '$21.49'},\n",
       "  'rating_breakdown': ['2', '0', '3', '12', '83'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/91P3C3+rx1L._AC_UY218_.jpg',\n",
       "  'title': \"A Lady's Guide to Fortune-Hunting: A Novel\",\n",
       "  'author': 'Sophie Irwin  | Jul 12, 2022',\n",
       "  'rating': '4.3',\n",
       "  'review_count': '2,386',\n",
       "  'product_link': '/Ladys-Guide-Fortune-Hunting-Novel-ebook/dp/B09JB7L18C/ref=sr_1_64?qid=1680261389&sr=8-64&srs=17296221011',\n",
       "  'publisher': 'Pamela Dorman Books',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$16.99',\n",
       "   'Paperback': '$17.00'},\n",
       "  'rating_breakdown': ['1', '3', '13', '35', '49'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/71duwitbLBL._AC_UY218_.jpg',\n",
       "  'title': 'Book Lovers',\n",
       "  'author': 'Emily Henry  | May 3, 2022',\n",
       "  'rating': '4.5',\n",
       "  'review_count': '58,450',\n",
       "  'product_link': '/Book-Lovers-Emily-Henry-ebook/dp/B09BTQ9HW6/ref=sr_1_66?qid=1680261489&sr=8-66&srs=17296221011',\n",
       "  'publisher': 'Berkley',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$9.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$16.99',\n",
       "   'Paperback': '$9.99'},\n",
       "  'rating_breakdown': ['1', '2', '9', '27', '61'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81wjlf+1Z8L._AC_UY218_.jpg',\n",
       "  'title': 'Bad City: Peril and Power in the City of Angels',\n",
       "  'author': 'Paul Pringle  | Jul 19, 2022',\n",
       "  'rating': '4.5',\n",
       "  'review_count': '752',\n",
       "  'product_link': '/Bad-City-Peril-Power-Angels/dp/1250824087/ref=sr_1_67?qid=1680261489&sr=8-67&srs=17296221011',\n",
       "  'publisher': 'Celadon Books',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$16.99',\n",
       "   'Paperback': '$18.00',\n",
       "   'Spiral-bound': '$50.94'},\n",
       "  'rating_breakdown': ['2', '1', '7', '27', '63'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/71u0oWneSUL._AC_UY218_.jpg',\n",
       "  'title': 'Butts: A Backstory',\n",
       "  'author': 'Heather Radke  | Nov 29, 2022',\n",
       "  'rating': '4.0',\n",
       "  'review_count': '115',\n",
       "  'product_link': '/Butts-Backstory-Heather-Radke/dp/1982135484/ref=sr_1_68?qid=1680261489&sr=8-68&srs=17296221011',\n",
       "  'publisher': 'Avid Reader Press / Simon & Schuster',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$20.49',\n",
       "   'Paperback': '$18.99',\n",
       "   'Audio': '$31.68'},\n",
       "  'rating_breakdown': ['3', '9', '18', '23', '47'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81p7iel7fpL._AC_UY218_.jpg',\n",
       "  'title': \"Raising Lazarus: Hope, Justice, and the Future of America's Overdose Crisis\",\n",
       "  'author': 'Beth Macy  | Aug 16, 2022',\n",
       "  'rating': '4.5',\n",
       "  'review_count': '110',\n",
       "  'product_link': '/Raising-Lazarus-Justice-Americas-Overdose-ebook/dp/B09N3GVQ3G/ref=sr_1_69?qid=1680261489&sr=8-69&srs=17296221011',\n",
       "  'publisher': 'Little, Brown and Company',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$15.71',\n",
       "   'Paperback': '$19.99',\n",
       "   'Audio': '$45.00'},\n",
       "  'rating_breakdown': ['3', '4', '7', '16', '70'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81WqM47lDhL._AC_UY218_.jpg',\n",
       "  'title': 'The Last Slave Ship: The True Story of How Clotilda Was Found, Her Descendants, and an Extraordinary Reckoning',\n",
       "  'author': 'Ben Raines  | Jan 25, 2022',\n",
       "  'rating': '4.6',\n",
       "  'review_count': '780',\n",
       "  'product_link': '/Last-Slave-Ship-Descendants-Extraordinary/dp/1982136049/ref=sr_1_70?qid=1680261489&sr=8-70&srs=17296221011',\n",
       "  'publisher': 'Simon & Schuster',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$13.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$9.44',\n",
       "   'Paperback': '$13.95',\n",
       "   'Audio': '$24.93'},\n",
       "  'rating_breakdown': ['0', '2', '5', '20', '73'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81bUOXfKm-L._AC_UY218_.jpg',\n",
       "  'title': 'Gilded Mountain: A Novel',\n",
       "  'author': 'Kate Manning  | Nov 1, 2022',\n",
       "  'rating': '4.3',\n",
       "  'review_count': '451',\n",
       "  'product_link': '/Gilded-Mountain-Novel-Kate-Manning-ebook/dp/B09RX2RSSS/ref=sr_1_71?qid=1680261489&sr=8-71&srs=17296221011',\n",
       "  'publisher': 'Scribner',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$13.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$19.29',\n",
       "   'Paperback': '$18.00',\n",
       "   'Audio': '$36.59'},\n",
       "  'rating_breakdown': ['2', '3', '10', '35', '50'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81JdbR46YlL._AC_UY218_.jpg',\n",
       "  'title': 'The Man Who Could Move Clouds: A Memoir',\n",
       "  'author': 'Ingrid Rojas Contreras  | Jul 12, 2022',\n",
       "  'rating': '4.4',\n",
       "  'review_count': '176',\n",
       "  'product_link': '/Man-Who-Could-Move-Clouds/dp/0385546661/ref=sr_1_72?qid=1680261489&sr=8-72&srs=17296221011',\n",
       "  'publisher': 'Doubleday',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$22.49',\n",
       "   'Paperback': '$17.00'},\n",
       "  'rating_breakdown': ['1', '5', '11', '22', '61'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/71ftXOmRB0L._AC_UY218_.jpg',\n",
       "  'title': 'In Love: A Memoir of Love and Loss',\n",
       "  'author': 'Amy Bloom  | Mar 8, 2022',\n",
       "  'rating': '4.5',\n",
       "  'review_count': '3,353',\n",
       "  'product_link': '/Love-Memoir-Loss-ebook/dp/B096XGDWSX/ref=sr_1_73?qid=1680261489&sr=8-73&srs=17296221011',\n",
       "  'publisher': 'Random House',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$2.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$23.99',\n",
       "   'Paperback': '$16.20'},\n",
       "  'rating_breakdown': ['1', '2', '8', '20', '69'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/91NOQ55v6VL._AC_UY218_.jpg',\n",
       "  'title': 'The Come Up: An Oral History of the Rise of Hip-Hop',\n",
       "  'author': 'Jonathan Abrams  | Oct 18, 2022',\n",
       "  'rating': '4.5',\n",
       "  'review_count': '42',\n",
       "  'product_link': '/Come-Up-Oral-History-Hip-Hop-ebook/dp/B09RF3R231/ref=sr_1_74?qid=1680261489&sr=8-74&srs=17296221011',\n",
       "  'publisher': 'Crown',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$13.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$24.49',\n",
       "   'Paperback': '$23.52'},\n",
       "  'rating_breakdown': ['0', '4', '6', '26', '64'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81NdR0rVXDL._AC_UY218_.jpg',\n",
       "  'title': 'Our Crooked Hearts: A Novel',\n",
       "  'author': 'Melissa Albert  | Jun 28, 2022',\n",
       "  'rating': '4.3',\n",
       "  'review_count': '625',\n",
       "  'product_link': '/Our-Crooked-Hearts-Melissa-Albert-ebook/dp/B09HJXT4KW/ref=sr_1_76?qid=1680261489&sr=8-76&srs=17296221011',\n",
       "  'publisher': 'Flatiron Books',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$10.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$1.49',\n",
       "   'Paperback': '$12.99'},\n",
       "  'rating_breakdown': ['1', '1', '15', '33', '50'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81bRujOgt7L._AC_UY218_.jpg',\n",
       "  'title': 'How to Speak Whale: A Voyage into the Future of Animal Communication',\n",
       "  'author': 'Tom Mustill  | Sep 6, 2022',\n",
       "  'rating': '4.5',\n",
       "  'review_count': '93',\n",
       "  'product_link': '/How-Speak-Whale-Voyage-Communication-ebook/dp/B09PL5H8TT/ref=sr_1_77?qid=1680261489&sr=8-77&srs=17296221011',\n",
       "  'publisher': 'Grand Central Publishing',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$24.99',\n",
       "   'Paperback': '$18.99',\n",
       "   'Audio': '$26.74'},\n",
       "  'rating_breakdown': ['4', '0', '9', '17', '70'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/91T5iorvFbL._AC_UY218_.jpg',\n",
       "  'title': 'Corrections in Ink: A Memoir',\n",
       "  'author': 'Keri Blakinger  | Jun 7, 2022',\n",
       "  'rating': '4.6',\n",
       "  'review_count': '686',\n",
       "  'product_link': '/Corrections-Ink-Memoir-Keri-Blakinger/dp/1250272858/ref=sr_1_78?qid=1680261489&sr=8-78&srs=17296221011',\n",
       "  'publisher': \"St. Martin's Press\",\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$15.99',\n",
       "   'Paperback': '$19.00'},\n",
       "  'rating_breakdown': ['1', '1', '6', '20', '73'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81m4dJ8d9-L._AC_UY218_.jpg',\n",
       "  'title': 'Acceptance: A Memoir',\n",
       "  'author': 'Emi Nietfeld  | Aug 2, 2022',\n",
       "  'rating': '4.5',\n",
       "  'review_count': '439',\n",
       "  'product_link': '/Acceptance-Memoir-Emi-Nietfeld-ebook/dp/B09KXS5KKL/ref=sr_1_79?qid=1680261489&sr=8-79&srs=17296221011',\n",
       "  'publisher': 'Penguin Press',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99', 'Audiobook': '$0.00', 'Hardcover': '$10.28'},\n",
       "  'rating_breakdown': ['2', '1', '8', '22', '66'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81en0hLe2+L._AC_UY218_.jpg',\n",
       "  'title': 'Tanqueray',\n",
       "  'author': 'Brandon Stanton  and Stephanie Johnson | Jul 12, 2022',\n",
       "  'rating': '4.8',\n",
       "  'review_count': '2,252',\n",
       "  'product_link': '/Tanqueray-Brandon-Stanton/dp/1250278279/ref=sr_1_80?qid=1680261489&sr=8-80&srs=17296221011',\n",
       "  'publisher': \"St. Martin's Press\",\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$12.99', 'Audiobook': '$0.00', 'Hardcover': '$12.33'},\n",
       "  'rating_breakdown': ['1', '1', '4', '10', '84'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81SA3p4+x5L._AC_UY218_.jpg',\n",
       "  'title': \"Like, Comment, Subscribe: Inside YouTube's Chaotic Rise to World Domination\",\n",
       "  'author': 'Mark Bergen  | Sep 6, 2022',\n",
       "  'rating': '4.4',\n",
       "  'review_count': '126',\n",
       "  'product_link': '/Like-Comment-Subscribe-YouTubes-Domination/dp/0593296346/ref=sr_1_81?qid=1680261563&sr=8-81&srs=17296221011',\n",
       "  'publisher': 'Viking',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$15.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$20.49',\n",
       "   'Paperback': '$24.00'},\n",
       "  'rating_breakdown': ['1', '3', '13', '26', '57'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/71Bi-0uqa5L._AC_UY218_.jpg',\n",
       "  'title': 'The Hookup Plan',\n",
       "  'author': 'Book 3 of 3: Boyfriend Project   |  Farrah Rochon  | Aug 2, 2022',\n",
       "  'rating': '4.4',\n",
       "  'review_count': '658',\n",
       "  'product_link': '/Hookup-Plan-Farrah-Rochon-ebook/dp/B09N3F3WV5/ref=sr_1_82?qid=1680261563&sr=8-82&srs=17296221011',\n",
       "  'publisher': 'Forever',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$3.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Paperback': '$12.00',\n",
       "   'Audio': '$25.00'},\n",
       "  'rating_breakdown': ['0', '1', '9', '34', '56'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/91R769GgqeL._AC_UY218_.jpg',\n",
       "  'title': 'Lavender House: A Novel',\n",
       "  'author': 'Lev AC Rosen  | Oct 18, 2022',\n",
       "  'rating': '4.4',\n",
       "  'review_count': '320',\n",
       "  'product_link': '/Lavender-House-Lev-AC-Rosen-ebook/dp/B09NK7VYGF/ref=sr_1_83?qid=1680261563&sr=8-83&srs=17296221011',\n",
       "  'publisher': 'Forge Books',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$13.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$25.31',\n",
       "   'Paperback': '$17.99'},\n",
       "  'rating_breakdown': ['1', '2', '12', '29', '56'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/71KWFLSchiL._AC_UY218_.jpg',\n",
       "  'title': \"His Name Is George Floyd: One Man's Life and the Struggle for Racial Justice\",\n",
       "  'author': 'Robert Samuels  and Toluse Olorunnipa  | May 17, 2022',\n",
       "  'rating': '4.7',\n",
       "  'review_count': '218',\n",
       "  'product_link': '/His-Name-George-Floyd-Struggle/dp/0593490614/ref=sr_1_84?qid=1680261563&sr=8-84&srs=17296221011',\n",
       "  'publisher': 'Viking',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$23.99',\n",
       "   'Paperback': '$23.06'},\n",
       "  'rating_breakdown': ['2', '3', '4', '9', '83'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/71Ib87d4ARL._AC_UY218_.jpg',\n",
       "  'title': 'The Unsinkable Greta James: A Novel',\n",
       "  'author': 'Jennifer E. Smith  | Mar 1, 2022',\n",
       "  'rating': '4.3',\n",
       "  'review_count': '2,349',\n",
       "  'product_link': '/Unsinkable-Greta-James-Novel-ebook/dp/B096D6BCTF/ref=sr_1_85?qid=1680261563&sr=8-85&srs=17296221011',\n",
       "  'publisher': 'Ballantine Books',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$11.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$15.49',\n",
       "   'Paperback': '$17.00'},\n",
       "  'rating_breakdown': ['1', '3', '13', '37', '47'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81o0F4b9PdL._AC_UY218_.jpg',\n",
       "  'title': 'The First Kennedys: The Humble Roots of an American Dynasty',\n",
       "  'author': 'Neal Thompson  | Feb 22, 2022',\n",
       "  'rating': '4.3',\n",
       "  'review_count': '397',\n",
       "  'product_link': '/First-Kennedys-Humble-American-Dynasty-ebook/dp/B08NWRR59W/ref=sr_1_86?qid=1680261563&sr=8-86&srs=17296221011',\n",
       "  'publisher': 'Mariner Books',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$12.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$19.85',\n",
       "   'Paperback': '$21.99',\n",
       "   'Audio': '$28.00'},\n",
       "  'rating_breakdown': ['4', '3', '11', '26', '57'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/91XHumXWseL._AC_UY218_.jpg',\n",
       "  'title': 'The Two Lives of Sara: A Novel',\n",
       "  'author': 'Catherine Adel West  | Sep 6, 2022',\n",
       "  'rating': '4.2',\n",
       "  'review_count': '198',\n",
       "  'product_link': '/Two-Lives-Sara-Novel-ebook/dp/B09QQMXGYK/ref=sr_1_87?qid=1680261563&sr=8-87&srs=17296221011',\n",
       "  'publisher': 'Park Row',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$13.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$15.39',\n",
       "   'Paperback': '$16.99',\n",
       "   'Audio': '$23.52'},\n",
       "  'rating_breakdown': ['2', '2', '14', '35', '47'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/71cVYnvkN9L._AC_UY218_.jpg',\n",
       "  'title': 'Token Black Girl: A Memoir',\n",
       "  'author': 'Danielle Prescod  | Oct 1, 2022',\n",
       "  'rating': '4.2',\n",
       "  'review_count': '3,210',\n",
       "  'product_link': '/Token-Black-Girl-Danielle-Prescod-ebook/dp/B09KLLG3L2/ref=sr_1_88?qid=1680261563&sr=8-88&srs=17296221011',\n",
       "  'publisher': 'Little A',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$0.00',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$15.67',\n",
       "   'Paperback': '$10.99',\n",
       "   'Audio': '$13.72'},\n",
       "  'rating_breakdown': ['2', '4', '15', '29', '50'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81sNPbR+VwL._AC_UY218_.jpg',\n",
       "  'title': 'Cabin Fever: The Harrowing Journey of a Cruise Ship at the Dawn of a Pandemic',\n",
       "  'author': 'Michael Smith  and Jonathan Franklin  | Jun 21, 2022',\n",
       "  'rating': '4.5',\n",
       "  'review_count': '530',\n",
       "  'product_link': '/Cabin-Fever-Harrowing-Journey-Pandemic-ebook/dp/B09GW1HFDH/ref=sr_1_89?qid=1680261563&sr=8-89&srs=17296221011',\n",
       "  'publisher': 'Doubleday',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$24.49',\n",
       "   'Paperback': '$25.75'},\n",
       "  'rating_breakdown': ['1', '2', '7', '26', '64'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81fcapAK1sL._AC_UY218_.jpg',\n",
       "  'title': 'The Final Strife: Book One of The Ending Fire Trilogy',\n",
       "  'author': 'Book 1 of 2: The Ending Fire Trilogy   |  Saara El-Arifi  | Jun 21, 2022',\n",
       "  'rating': '4.6',\n",
       "  'review_count': '350',\n",
       "  'product_link': '/Final-Strife-Saara-El-Arifi-ebook/dp/B09HTH9QC3/ref=sr_1_90?qid=1680261563&sr=8-90&srs=17296221011',\n",
       "  'publisher': 'Del Rey',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$11.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$20.99',\n",
       "   'Paperback': '$18.00'},\n",
       "  'rating_breakdown': ['1', '2', '4', '23', '70'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81ChpDzmdjL._AC_UY218_.jpg',\n",
       "  'title': 'Paris Daillencourt Is About to Crumble (Winner Bakes All Book 2)',\n",
       "  'author': 'Book 2 of 3: Winner Bakes All   |  Alexis Hall  | Nov 1, 2022',\n",
       "  'rating': '4.1',\n",
       "  'review_count': '447',\n",
       "  'product_link': '/Paris-Daillencourt-About-Crumble-Winner-ebook/dp/B09RWNW6LD/ref=sr_1_91?qid=1680261563&sr=8-91&srs=17296221011',\n",
       "  'publisher': 'Forever',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$9.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Paperback': '$10.23',\n",
       "   'Audio': '$28.40'},\n",
       "  'rating_breakdown': ['0', '4', '19', '36', '40'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/71O2bNw-QSL._AC_UY218_.jpg',\n",
       "  'title': 'NSFW: A Novel',\n",
       "  'author': 'Isabel Kaplan  | Jul 5, 2022',\n",
       "  'rating': '3.7',\n",
       "  'review_count': '183',\n",
       "  'product_link': '/NSFW-Novel-Isabel-Kaplan-ebook/dp/B09C4FV185/ref=sr_1_92?qid=1680261563&sr=8-92&srs=17296221011',\n",
       "  'publisher': 'Henry Holt and Co.',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$13.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$19.23',\n",
       "   'Paperback': '$17.26'},\n",
       "  'rating_breakdown': ['2', '12', '27', '31', '28'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81tropLV-RS._AC_UY218_.jpg',\n",
       "  'title': 'Sleepwalk: A Novel',\n",
       "  'author': 'Dan Chaon  | May 24, 2022',\n",
       "  'rating': '4.0',\n",
       "  'review_count': '612',\n",
       "  'product_link': '/Sleepwalk-Novel-Dan-Chaon-ebook/dp/B092T8V4W1/ref=sr_1_93?qid=1680261563&sr=8-93&srs=17296221011',\n",
       "  'publisher': 'Henry Holt and Co.',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$14.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$16.99',\n",
       "   'Paperback': '$17.99'},\n",
       "  'rating_breakdown': ['3', '6', '19', '33', '39'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/71JmatnPSPL._AC_UY218_.jpg',\n",
       "  'title': 'The Year of the Horses: A Memoir',\n",
       "  'author': 'Courtney Maum  | Feb 14, 2023',\n",
       "  'rating': '4.1',\n",
       "  'review_count': '154',\n",
       "  'product_link': '/Year-Horses-Memoir-Courtney-Maum/dp/1953534821/ref=sr_1_94?qid=1680261563&sr=8-94&srs=17296221011',\n",
       "  'publisher': 'Tin House Books',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$13.49',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$25.11',\n",
       "   'Paperback': '$17.95',\n",
       "   'Audio': '$31.95'},\n",
       "  'rating_breakdown': ['6', '6', '12', '22', '53'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/91VEqtaf8YL._AC_UY218_.jpg',\n",
       "  'title': 'The Other Mother: A Novel',\n",
       "  'author': 'Rachel M. Harper  | May 3, 2022',\n",
       "  'rating': '4.4',\n",
       "  'review_count': '398',\n",
       "  'product_link': '/Other-Mother-Rachel-M-Harper-ebook/dp/B096DH78WQ/ref=sr_1_95?qid=1680261563&sr=8-95&srs=17296221011',\n",
       "  'publisher': 'Counterpoint',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$13.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$24.64',\n",
       "   'Paperback': '$18.95'},\n",
       "  'rating_breakdown': ['2', '3', '9', '31', '55'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/I/81HeVWjFY7L._AC_UY218_.jpg',\n",
       "  'title': 'How to Kill Your Family: A Novel',\n",
       "  'author': 'Bella Mackie  | Aug 2, 2022',\n",
       "  'rating': '4.0',\n",
       "  'review_count': '20,610',\n",
       "  'product_link': '/How-Kill-Your-Family-Novel-ebook/dp/B09S3S9K5P/ref=sr_1_96?qid=1680261563&sr=8-96&srs=17296221011',\n",
       "  'publisher': 'The Overlook Press',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$9.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$18.28',\n",
       "   'Paperback': '$13.50',\n",
       "   'Audio': '$25.30'},\n",
       "  'rating_breakdown': ['3', '6', '18', '29', '43'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/91Biub6GqqL._AC_UY218_.jpg',\n",
       "  'title': 'Such Big Dreams: A Novel',\n",
       "  'author': 'Reema Patel  | May 10, 2022',\n",
       "  'rating': '4.3',\n",
       "  'review_count': '255',\n",
       "  'product_link': '/Such-Big-Dreams-Reema-Patel-ebook/dp/B09H2NNGZV/ref=sr_1_98?qid=1680261638&sr=8-98&srs=17296221011',\n",
       "  'publisher': 'Ballantine Books',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$13.99',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$15.99',\n",
       "   'Paperback': '$18.00'},\n",
       "  'rating_breakdown': ['2', '0', '9', '38', '51'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/81pIr-oANIL._AC_UY218_.jpg',\n",
       "  'title': 'The Community: A Memoir',\n",
       "  'author': 'N. Jamiyla Chisholm  | Jun 1, 2022',\n",
       "  'rating': '3.9',\n",
       "  'review_count': '2,881',\n",
       "  'product_link': '/Community-N-Jamiyla-Chisholm-ebook/dp/B0976VRCV1/ref=sr_1_99?qid=1680261638&sr=8-99&srs=17296221011',\n",
       "  'publisher': 'Little A',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Kindle': '$0.00',\n",
       "   'Audiobook': '$0.00',\n",
       "   'Hardcover': '$12.70',\n",
       "   'Paperback': '$12.26',\n",
       "   'Audio': '$5.62'},\n",
       "  'rating_breakdown': ['4', '7', '22', '30', '37'],\n",
       "  'ranking': []},\n",
       " {'image': 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/71yazKQc-rL._AC_UY218_.jpg',\n",
       "  'title': 'By the Book-A Meant To Be Novel',\n",
       "  'author': '',\n",
       "  'rating': '4.4',\n",
       "  'review_count': '7',\n",
       "  'product_link': '/Book-Meant-be-Novel/dp/1368050395/ref=sr_1_100?qid=1680261638&sr=8-100&srs=17296221011',\n",
       "  'publisher': 'Hyperion Avenue',\n",
       "  'publish_date': 'Jan 1, 1970',\n",
       "  'prices': {'Hardcover': '$27.23'},\n",
       "  'rating_breakdown': ['0', '15', '0', '19', '66'],\n",
       "  'ranking': []}]"
      ]
     },
     "execution_count": 45,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "[r for r in result if r[\"ranking\"]==[]]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5e02b28a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "d2c9e572",
   "metadata": {},
   "outputs": [],
   "source": [
    "f = open('output-full.json', 'w')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "77bac828",
   "metadata": {},
   "outputs": [],
   "source": [
    "json.dump(result, f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "id": "44a6c9fb",
   "metadata": {},
   "outputs": [],
   "source": [
    "f.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "67792431",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
